package Robotronix.vision.ui;

import javax.swing.*;
import java.awt.*;
import org.opencv.core.*;

/**
 * Created by sysgen on 02/02/17.
 */
public class secondaryPane {

    public JPanel panel1;
    private JSlider hue1Slider;
    private JSlider saturation1Slider;
    private JSlider value1Slider;
    private JSlider hue2Slider;
    private JSlider saturation2Slider;
    private JSlider value2Slider;
    private JLabel hueFrom;
    private JLabel saturationFrom;
    private JLabel valueFrom;
    private JLabel hueTo;
    private JLabel saturationTo;
    private JLabel valueTo;
    private JSlider expostionSlider;
    private JCheckBox activerContrôleCheckBox;
    private JRadioButton mode1RadioButton;
    private JRadioButton mode2RadioButton;

    Scalar getFromSliderValues() {
        return new Scalar(hue1Slider.getValue(), saturation1Slider.getValue(),
                value1Slider.getValue());
    }

    Scalar getToSliderValues() {
        return new Scalar(hue2Slider.getValue(), saturation2Slider.getValue(),
                value2Slider.getValue());
    }

    boolean isControlActivated() {
        return activerContrôleCheckBox.isSelected();
    }

    double getExpostionValue() {
        return expostionSlider.getValue();
    }

    int getMode() {
        if (mode1RadioButton.isSelected()) {
            return 0;
        }
        return 1;
    }

    private void createUIComponents() {
    }

    public secondaryPane() {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        hue1Slider = new JSlider();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(hue1Slider, gbc);
        saturation1Slider = new JSlider();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(saturation1Slider, gbc);
        value1Slider = new JSlider();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(value1Slider, gbc);
        hue2Slider = new JSlider();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(hue2Slider, gbc);
        saturation2Slider = new JSlider();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(saturation2Slider, gbc);
        value2Slider = new JSlider();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(value2Slider, gbc);
        hueFrom = new JLabel();
        hueFrom.setText("H1");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(hueFrom, gbc);
        saturationFrom = new JLabel();
        saturationFrom.setText("S1");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(saturationFrom, gbc);
        valueFrom = new JLabel();
        valueFrom.setText("V1");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(valueFrom, gbc);
        hueTo = new JLabel();
        hueTo.setText("H2");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(hueTo, gbc);
        saturationTo = new JLabel();
        saturationTo.setText("S2");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(saturationTo, gbc);
        expostionSlider = new JSlider();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(expostionSlider, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Exposition");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label1, gbc);
        valueTo = new JLabel();
        valueTo.setText("V2");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(valueTo, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer1, gbc);
        activerContrôleCheckBox = new JCheckBox();
        activerContrôleCheckBox.setText("Activer contrôle");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        panel1.add(activerContrôleCheckBox, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer2, gbc);
        mode1RadioButton = new JRadioButton();
        mode1RadioButton.setText("Mode 1");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(mode1RadioButton, gbc);
        mode2RadioButton = new JRadioButton();
        mode2RadioButton.setText("Mode 2");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(mode2RadioButton, gbc);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(mode1RadioButton);
        buttonGroup.add(mode2RadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
